append = pack
label = json-import

# load some plugins to activate some statements
[use]
plugin = basics
plugin = analytics

; since lodex@12.23
[unpack]

[replace]
path = id
value = get("publicUrl")

path = value
value = self()

[aggregate]

[assign]
path = latest
value = get("value").maxBy(obj => \
  new Date( \
    obj.dateImport.split(' ')[2], \
    { \
      janvier:0, \
      février:1, \
      mars:2, \
      avril:3, \
      mai:4, \
      juin:5, \
      juillet:6, \
      août:7, \
      septembre:8, \
      octobre:9, \
      novembre:10, \
      décembre:11 \
    }[obj.dateImport.split(' ')[1].toLowerCase()], \
    obj.dateImport.split(' ')[0] \
  ) \
).omit(["uri"])

[exchange]
value = get("latest")

# Ensures that each object contains an identification key (required by lodex)
[swing]
test = pick(['URI', 'uri']).pickBy(_.identity).isEmpty()
[swing/identify]

# Ignore objects with duplicate URI
[dedupe]
ignore = true

# Prevent keys from containing dot path notation (which is forbidden by nodejs mongoDB driver)
[OBJFlatten]
separator = fix('.')
reverse = true
safe = true

# Uncomment to see each data sent to the database
#[debug]

# Add contextual metadata related to the import
[assign]
path = dateMiseAJour
value = fix(new Date()) \
  .thru(d => new Intl.DateTimeFormat('fr-FR', { \
    year: 'numeric', \
    month: 'long', \
    day: 'numeric', \
  }).format(d))

[assign]
path = statut
value = get("dateMiseAJour").thru(date => date === self.dateImport ? "Ouverte" : "Supprimée")