append = pack
label = json-lines

# load some plugins to activate some statements
[use]
plugin = basics

[unpack]

[env]
path =dictionnary
value = fix({"A. Kremer" : "APIL", \
             "J. Mourot" : "APIL", \
             "P. Ranoarisoa" : "APIL", \
             "C. Gay" : "APIL", \
             "E. Giret" : "APIL", \
             "S. Barreaux" : "ISTEX" ,\
             "E. Caule" : "ISTEX" ,\
             "M. Huguin" : "ISTEX" ,\
             "P. Viot" : "ISTEX" ,\
             "P. Cuxac" : "TDM",\
             "N. Thouvenin" : "DAFIS"\
})

[exchange]
value = get("instance")

[remove]
test = get("technicalName").thru(name => name !== "instance-globale-161010")

[exchange]
value = get("tenant")

[assign]
path = service
value = get("author").thru(status => env("dictionnary")[status] ?? "inconnu")

path = datePourGraph
value = get("createdAt").slice(0, 7).join("")

path = published
value = get("published").thru(bool => bool === true ? "Oui" : "Non")

path = hasData
value = get("dataset").thru(v => v === 0 ? "Non" : "Oui")

path = mailToContact
value = get("description").split(";").last().trim().thru(v => _.includes(v,"@") ? v : "Pas de mail")

path = dateImport
value = fix(new Date()) \
  .thru(d => new Intl.DateTimeFormat('fr-FR', { \
    year: 'numeric', \
    month: 'long', \
    day: 'numeric', \
  }).format(d))

path = instanceUrl
value = fix(`https://lodex.istex.fr/instance/${self.name}`)

path = verbalizedCreatedDate
value = get("createdAt").thru(d => new Intl.DateTimeFormat('fr-FR', { \
    year: 'numeric', \
    month: 'long' \
  }).format(new Date(d)))

[assign]
path = fieldsForTemplate
value = fix(self.service, self.instanceUrl, self.verbalizedCreatedDate, self.mailToContact, self.published, self.hasData)
[remove]
test=fix(self.name,self.author).join("|").isEqual("default|Root")

[exchange]
value = omit(["username","password","totalSize"])

# Ensures that each object contains an identification key (required by lodex)
[swing]
test = pick(['URI', 'uri']).pickBy(_.identity).isEmpty()
[swing/identify]

# Ignore objects with duplicate URI
[dedupe]
ignore = true

# Prevent keys form containing dot path notation (which is forbidden by nodejs mongoDB driver)
[OBJFlatten]
separator = fix('.')
reverse = true